### ISSUE TITLE
Make API "service" classes into singletons

### ISSUE THREAD

**Issue by hades200082** [hades200082/template-app-infrastructure#15]
My thinking here is to ensure that only one instance of each class exists in memory ever.

I think we can achieve this by NOT exporting the class itself but rather, exporting a new instance of the class at the bottom of the file.

```typescript
/// MyClass.ts
class MyClass {
    constructor() {
        // do stuff
    }

    myFunc() {
        // do other stuff
    }
}

export default const instance = new MyClass();
```

```typescript
/// some-other-file.ts
import MyClass from "path/to/MyClass"

// stuff

// call our class
MyClass.myFunc();
```

**Comment by hades200082** [comment]
@styles102 I'd welcome your thoughts on this one

**Comment by styles102** [comment]
seems like it should work. we could certainly trial it and see wat happens
